apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: default
  labels:
    migrated-from: app-engine
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations: {}
    spec:
      containers:
        - image: gcr.io/maucaro-sandbox/image
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: maucaro-sandbox
      serviceAccountName: maucaro-sandbox@appspot.gserviceaccount.com